require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe CommentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Comment. As you add validations to Comment, be sure to
  # adjust the attributes here as well.
  let(:flower) { Flower.create!(title: "My flower", description: "Some desc") }

  let(:valid_attributes) {
    {
      flower_id: flower.id,
      author: "me",
      body: "Lorem ipsum",
      vote: 3
    }
  }

  let(:invalid_attributes) {
    {
      vote: 10
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      comment = Comment.create! valid_attributes
      get :index, params: {flower_id: flower.id, }, session: valid_session, format: :json
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      comment = Comment.create! valid_attributes
      get :show, params: {flower_id: flower.id, id: comment.to_param}, session: valid_session, format: :json
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {flower_id: flower.id, }, session: valid_session, format: :json
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      comment = Comment.create! valid_attributes
      get :edit, params: {flower_id: flower.id, id: comment.to_param}, session: valid_session, format: :json
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Comment" do
        expect {
          post :create, params: {flower_id: flower.id, comment: valid_attributes}, session: valid_session, format: :json
        }.to change(Comment, :count).by(1)
      end
    end

    context "with invalid params" do
      it "returns invalid params response" do
        post :create, params: {flower_id: flower.id, comment: invalid_attributes}, session: valid_session, format: :json
        expect(response).to be_success
        expect(response.status).to eq(422)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested comment" do
        comment = Comment.create! valid_attributes
        put :update, params: {flower_id: flower.id, id: comment.to_param, comment: new_attributes}, session: valid_session, format: :json
        comment.reload
        skip("Add assertions for updated state")
      end
    end

    context "with invalid params" do
      it "returns invalid params response" do
        comment = Comment.create! valid_attributes
        put :update, params: {flower_id: flower.id, id: comment.to_param, comment: invalid_attributes}, session: valid_session, format: :json
        expect(response.status).to eq(422)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested comment" do
      comment = Comment.create! valid_attributes
      expect {
        delete :destroy, params: {flower_id: flower.id, id: comment.to_param}, session: valid_session, format: :json
      }.to change(Comment, :count).by(-1)
    end
  end

end
